### ISSUE TITLE
Request SQ610RF - humidity - Battery

### ISSUE THREAD

**Issue by albei** [konradb3/homeassistant_salus#13]
Hello!
First of all, you did an awesome thing with this integration! 
Thanks!
Is it possible to have humidity and batter from sq610rf as sensors in homeassistant? 
So we can automate more things based on them.

Once again, thanks!

**Comment by jvitkauskas** [comment]
Hi, I am the author of the underlying library which is used by this integration. I don't have SQ610RF myself and I think I have not seen humidity in the data. So you'll need to run main.py from here https://github.com/jvitkauskas/pyit600 and send me the output together with current humidity value so I could try to find it.

As for battery - the gateway provides only the voltage (and HA expects percents) so I would need to hardcode thresholds for each device which I have avoided doing so far.

BTW, does the Salus app show humidity?

**Comment by albei** [comment]
I posted an req on your repository. Gonna close this one and continue there.
